project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  plos-pdf:
    number-sections: true
    journal:
      # This is an identifier for the target journal: 
      # from https://plos.org/resources/writing-center/ following submission guidelines link, the identifier is the part of the URL after https://journals.plos.org/<id>/s/submission-guidelines
      id: ploscompbiol
    include-in-header:
      text: |
          \usepackage{setspace} 
          \doublespacing

execute:
  freeze: auto

preview:
  navigate: false

