project:
  type: manuscript

manuscript:
  article: index.qmd

lang: en-CA

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  cerg-typst: default
  
execute:
  freeze: auto

preview:
  navigate: false
